### ISSUE TITLE
Github widget in header appears with inconsistent styles

### ISSUE THREAD

**Issue by seand7565** [solidusio/solidus-site#356]
(*This issue has changed slightly since posting - see comment below*)

On blog posts, the github widget in the header doesn't appear, instead we just get text that says "Star" - see below, blog index page vs. blog show page. As far as I can tell this only happens on the blog show page.

![image](https://user-images.githubusercontent.com/5720486/90423032-63eb7600-e081-11ea-9acd-f04c7f258048.png)

![image](https://user-images.githubusercontent.com/5720486/90423039-65b53980-e081-11ea-8667-b0f42de02466.png)

**Comment by seand7565** [comment]
Looks like this has changed slightly - I will update the issue title to reflect, but now the github stars always appear - it's just that it's inconsistent from a blog show page to any other page.

On any other page:
<img width="238" alt="Screen Shot 2020-09-11 at 7 53 02 AM" src="https://user-images.githubusercontent.com/5720486/92927905-f4f50900-f403-11ea-8b3f-368c50c5a85f.png">

On a blog show page:
<img width="231" alt="Screen Shot 2020-09-11 at 7 53 06 AM" src="https://user-images.githubusercontent.com/5720486/92927911-f7eff980-f403-11ea-9bb5-bcc7cbbda508.png">

**Comment by davidedistefano** [comment]
@seand7565 thanks for reporting this. We'll fix it soon!
